services:
  mysql:
    image: mysql:8.0
    container_name: webchecker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webcheckerdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webchecker-network

volumes:
  mysql-data:

networks:
  webchecker-network: